format:
  html: {toc: true, toc-depth: 3, theme: united, number-sections: false}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, notebooks/common_ints.ipynb, common_ints.qmd]
  title: 'CS5200: Background & Expectations'
